/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class emshop_EmshopNativeInterface */

#ifndef _Included_emshop_EmshopNativeInterface
#define _Included_emshop_EmshopNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    initializeService
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_initializeService
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getInitializationStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getInitializationStatus
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_login
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    register
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_register
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    logout
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_logout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    updateUserInfo
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_updateUserInfo
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getProductList
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getProductList
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getProductDetail
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getProductDetail
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    addProduct
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_addProduct
  (JNIEnv *, jclass, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    updateProduct
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_updateProduct
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    deleteProduct
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_deleteProduct
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getCategories
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getCategories
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getCategoryProducts
 * Signature: (Ljava/lang/String;IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getCategoryProducts
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    searchProducts
 * Signature: (Ljava/lang/String;IILjava/lang/String;DD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_searchProducts
  (JNIEnv *, jclass, jstring, jint, jint, jstring, jdouble, jdouble);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    updateStock
 * Signature: (JILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_updateStock
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    checkStock
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_checkStock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getLowStockProducts
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getLowStockProducts
  (JNIEnv *, jclass, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    addToCart
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_addToCart
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getCart
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getCart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    removeFromCart
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_removeFromCart
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    updateCartItemQuantity
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_updateCartItemQuantity
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    clearCart
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_clearCart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    updateCartSelected
 * Signature: (JJZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_updateCartSelected
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getCartSummary
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getCartSummary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    checkout
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_checkout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getOrderList
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getOrderList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getOrderDetail
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getOrderDetail
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    cancelOrder
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_cancelOrder
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    deleteOrder
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_deleteOrder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    updateOrderStatus
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_updateOrderStatus
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getOrdersByStatus
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getOrdersByStatus
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    trackOrder
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_trackOrder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    payOrder
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_payOrder
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    confirmDelivery
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_confirmDelivery
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    requestRefund
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_requestRefund__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getAllOrders
 * Signature: (Ljava/lang/String;IILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getAllOrders
  (JNIEnv *, jclass, jstring, jint, jint, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getActivePromotions
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getActivePromotions
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    createPromotion
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_createPromotion
  (JNIEnv *, jclass, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    calculateDiscount
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_calculateDiscount
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    applyCoupon
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_applyCoupon
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    createAfterSaleRequest
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_createAfterSaleRequest
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getAfterSaleRequests
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getAfterSaleRequests
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    processAfterSaleRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_processAfterSaleRequest
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getAvailableThemes
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getAvailableThemes
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    setUserTheme
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_setUserTheme
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserTheme
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserTheme
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    acquireProductLock
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_acquireProductLock
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    releaseProductLock
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_releaseProductLock
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getProductLockStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getProductLockStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    setProductLimitQuantity
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_setProductLimitQuantity
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getSalesStatistics
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getSalesStatistics
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserBehaviorAnalysis
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserBehaviorAnalysis
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getPopularProducts
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getPopularProducts
  (JNIEnv *, jclass, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserRoles
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserRoles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    setUserRole
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_setUserRole
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    checkUserPermission
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_checkUserPermission
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    verifyAdminPermission
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_verifyAdminPermission
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserDetailWithPermissions
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserDetailWithPermissions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    processPayment
 * Signature: (JLjava/lang/String;DLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_processPayment
  (JNIEnv *, jclass, jlong, jstring, jdouble, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getPaymentStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getPaymentStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    refundPayment
 * Signature: (JDLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_refundPayment
  (JNIEnv *, jclass, jlong, jdouble, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getServerStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getServerStatus
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getSystemLogs
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getSystemLogs
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getSystemMetrics
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getSystemMetrics
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getActiveConnections
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getActiveConnections
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    executeDMLQuery
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_executeDMLQuery
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    executeSelectQuery
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_executeSelectQuery
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getDatabaseSchema
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getDatabaseSchema
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    executeBatch
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_executeBatch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    addUserAddress
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_addUserAddress
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserAddresses
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserAddresses
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    updateUserAddress
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_updateUserAddress
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    deleteUserAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_deleteUserAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    setDefaultAddress
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_setDefaultAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    createOrderFromCart
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_createOrderFromCart
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    createOrderDirect
 * Signature: (JJIJLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_createOrderDirect
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    shipOrder
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_shipOrder
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    completeOrder
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_completeOrder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    requestRefund
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_requestRefund__JJLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getAvailableCoupons
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getAvailableCoupons
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserCoupons
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserCoupons
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    claimCoupon
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_claimCoupon
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    useCoupon
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_useCoupon
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    validateCoupon
 * Signature: (JLjava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_validateCoupon
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    addProductReview
 * Signature: (JJJILjava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_addProductReview
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jstring, jboolean);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getProductReviews
 * Signature: (JIILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getProductReviews
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserReviews
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserReviews
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    reviewProductReview
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_reviewProductReview
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    deleteProductReview
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_deleteProductReview
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getReviewStatistics
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getReviewStatistics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getAllUsers
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getAllUsers
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    searchUsers
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_searchUsers
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    setUserStatus
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_setUserStatus
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    assignCoupon
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_assignCoupon
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    banUser
 * Signature: (JLjava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_banUser
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    unbanUser
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_unbanUser
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getSystemStatistics
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getSystemStatistics
  (JNIEnv *, jclass, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    clearCache
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_clearCache
  (JNIEnv *, jclass, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getCacheStats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getCacheStats
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    approveRefund
 * Signature: (JJZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_approveRefund
  (JNIEnv *, jclass, jlong, jlong, jboolean, jstring);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getRefundRequests
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getRefundRequests
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getUserRefundRequests
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getUserRefundRequests
  (JNIEnv *, jclass, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getNotifications
 * Signature: (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getNotifications
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    markNotificationRead
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_markNotificationRead
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getAvailableCouponsForOrder
 * Signature: (JD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getAvailableCouponsForOrder
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    calculateCouponDiscount
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_calculateCouponDiscount
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    createCouponActivity
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DDILjava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_createCouponActivity
  (JNIEnv *, jclass, jstring, jstring, jstring, jdouble, jdouble, jint, jstring, jstring, jlong);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    getCouponTemplates
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_getCouponTemplates
  (JNIEnv *, jclass);

/*
 * Class:     emshop_EmshopNativeInterface
 * Method:    distributeCouponsToUsers
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_emshop_EmshopNativeInterface_distributeCouponsToUsers
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
